### ISSUE TITLE
Access the EPRuntime only through the DecisionEngine

### ISSUE THREAD

**Issue by tscurtu** [CatalinRamascanu/autonomous-dynamic-decision-engine#6]
Currently the fetcher sends events directly to the EPRuntime. If we need to add hooks for preprocessing when ingesting events, we would need a central point of insertion.

Please create a method in the DecisionEngine that proxies all event inputs and delegates them to the EPRuntime. The EPRuntime should be isolated and encapsulated by the DecisionEngine.

**Comment by CatalinRamascanu** [comment]
Should the fetcher receive the instance of DecisionEngine instead of EPRuntime? I am thinking of calling addInputData method from DecisionEngine for inserting data in the engine.

**Comment by tscurtu** [comment]
Yes, I think that is the way to go.
